apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    
    
    @INCLUDE input-kubernetes-ingress-controller.conf
    @INCLUDE filter-kubernetes-ingress-controller.conf
    @INCLUDE output-elasticsearch-ingress-controller.conf
    @INCLUDE input-kubernetes-apps.conf
    @INCLUDE filter-kubernetes-apps.conf
    @INCLUDE filter-modify.conf
    @INCLUDE output-elasticsearch-apps.conf

  input-kubernetes-ingress-controller.conf: |
    [INPUT]
        Name              tail
        Tag               ic.*
        Path              /var/log/containers/aws-load-balancer-controller-*.log
        Parser            cri
        Docker_Mode       On
        DB                /var/log/flb_kube_cma_be.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   Off
        Refresh_Interval  5

  filter-kubernetes-ingress-controller.conf: |
    [FILTER]
        Name                kubernetes
        Match               ic.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       jlog
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Buffer_Size         0  
        Use_Kubelet         true   
        Kubelet_Port        10250
        Labels              On
        DNS_Retries         3
        DNS_Wait_Time       10

  output-elasticsearch-ingress-controller.conf: |
    [OUTPUT]
        Name                es
        Match               ic.*
        Host                ${OS_DOMAIN_HOST}
        Port                443
        HTTP_User           ${OS_AUTH_USER}
        HTTP_Passwd         ${OS_AUTH_PASS}
        Logstash_Format     Off
        index               k8s-apps-
        Replace_Dots        On
        Suppress_Type_Name  On
        Retry_Limit         10
        Trace_Error         On  
        Trace_Output        On
        tls                 On
        tls.verify          Off


  input-kubernetes-apps.conf: |
    [INPUT]
        Name              tail
        Tag               apps.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/aws-load-balancer-controller-*.log, /var/log/containers/aws-node-*.log,/var/log/containers/coredns-*.log, /var/log/containers/fluent-bit-*.log, /var/log/containers/cma-frontend-service-*.log, /var/log/containers/cma-backend-service-*.log, /var/log/containers/csi-snapshotter-*.log
        Parser            cri
        Docker_Mode       On
        DB                /var/log/flb_kube_app.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   Off
        Refresh_Interval  10

  filter-kubernetes-apps.conf: |
    [FILTER]
        Name                kubernetes
        Match               apps.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       jlog
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off 
        Buffer_Size         0  
        Use_Kubelet         true   
        Kubelet_Port        10250
        Labels              On
        DNS_Retries         3
        DNS_Wait_Time       10

  filter-modify.conf: |
    [FILTER]
        Name modify
        Match *
        Add cluster         ${K8S_CLUSTER_NAME}
        Add environment     ${K8S_CLUSTER_ENV}

  output-elasticsearch-apps.conf: |
    [OUTPUT]
        Name                es
        Match               apps.*
        Host                ${OS_DOMAIN_HOST}
        Port                443
        HTTP_User           ${OS_AUTH_USER}
        HTTP_Passwd         ${OS_AUTH_PASS}
        Logstash_Format     Off
        index               k8s-apps-
        Pipeline            event_rename
        Replace_Dots        On
        Suppress_Type_Name  On
        Retry_Limit         10
        Trace_Error         On  
        Trace_Output        On
        tls                 On
        tls.verify          Off

  output-elasticsearch-cma-fe.conf: |
    [OUTPUT]
        Name                es
        Match               cma.fe.*
        Host                ${OS_DOMAIN_HOST}
        Port                443
        HTTP_User           ${OS_AUTH_USER}
        HTTP_Passwd         ${OS_AUTH_PASS}
        Logstash_Format     Off
        index               k8s-apps-
        Pipeline            k8s_cma_fe_test_convert
        Replace_Dots        On
        Suppress_Type_Name  On
        Retry_Limit         10
        Trace_Error         On  
        tls                 On
        tls.verify          Off

  parsers.conf: |-
    [PARSER]
    # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error_change
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    
    [PARSER]
        Name   nginx2
        Format regex
        Regex  ^(\[(?<time>[^\]]*)\]) (?<remote>[^ ]*) [^ ]* (?<user>[^ ]*) - (?<server>[^ ]*) to:(?<upstream>[^ ]*) [^ ]* (?<method>\S+) (?<path>[^\"]*?) (?<code>[^\"]*?) (?<response_time_desc>[^\"]*) (?<response_time_value>[^\"]*) (?<response_time_unit>[^\"]*) (?<response_time_ms>[^\"]*) (?<request_time_desc>[^\"]*) (?<request_time_value>[^\"]*)
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    
    [PARSER]
        Name   json2
        Format json
        Time_Key @timestamp
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
