apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    reloader.stakater.com/auto: "true"
  generation: 2
  labels:
    k8s-app: fluent-bit-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  name: fluent-bit
  namespace: monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-12-18T19:21:46Z"
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: fluent-bit-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
        - image: fluent/fluent-bit:3.0.6
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          ports:
            - containerPort: 2020
              hostPort: 2020
              protocol: TCP
          env:
            - name: K8S_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: k8s.cluster.name
            - name: K8S_CLUSTER_ENV
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: k8s.cluster.env
            - name: OS_DOMAIN_HOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: os.domain.host
            - name: OS_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: opensearch-access
                  key: username
                  optional: false
            - name: OS_AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: opensearch-access
                  key: password
                  optional: false
            - name: HTTP_SERVER
              value: 'On'
            - name: HTTP_PORT
              value: '2020'
            - name: READ_FROM_HEAD
              value: 'Off'
            - name: READ_FROM_TAIL
              value: 'On'
            - name: HOST_NAME
              value: 0.0.0.0
            - name: CI_VERSION
              value: "k8s/1.3.8"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /fluent-bit/etc/
              name: fluent-bit-config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - configMap:
            defaultMode: 420
            name: fluent-bit-config
          name: fluent-bit-config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

