# values-zabbix.yaml
zabbix-server:
  enabled: true
  image:
    tag: alpine-6.4.5
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  persistence:
    enabled: true
    storageClassName: standard
    size: 10Gi

zabbix-web:
  enabled: true
  image:
    tag: alpine-6.4.5
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - zabbix.minikube.local
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

#zabbix-agent:
#  enabled: false
#  resources:
#    requests:
#      memory: 64Mi
#      cpu: 50m
#    limits:
#      memory: 128Mi
#      cpu: 100m

postgresql:
  enabled: true
  auth:
    username: zabbix
    password: "zabbix-password"
    database: zabbix
  persistence:
    enabled: true
    storageClassName: standard
    size: 20Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# Prometheus integration configuration
prometheus:
  enabled: true
  url: "http://prometheus.local:9090"